version: "3.7"

services:
  api:
    build: "./cortex/api"
    ports:
      - 5000:5000
    command: "-h 0.0.0.0 -d mongodb://database:27017"
    networks:
      - cortex-net
    depends_on:
      - database
    volumes: 
        - "cortex-data:/var/lib/data"

  mq:
    image: "rabbitmq"
    ports:
      - 5672:5672
    networks:
      - cortex-net

  database:
    image: "mongo"
    ports:
      - 27017:27017
    networks:
      - cortex-net
    volumes:
      - "cortex-data:/var/lib/db"

  server:
    build: "./cortex/server"
    ports:
      - 8000:8000
    command: "-h 0.0.0.0 rabbitmq://mq:5672"
    networks:
      - cortex-net
    depends_on:
      - mq
    volumes:
      - "cortex-data:/var/lib/data"
    environment: 
        SHARED_SAVE_PATH: "/var/lib/data"

  saver:
    build: "./cortex/saver"
    command: "mongodb://database:27017 rabbitmq://mq:5672"
    networks:
      - cortex-net
    depends_on:
      - database
      - mq
    restart: on-failure

  gui:
    build: "./cortex/gui"
    command: "-h 0.0.0.0 -H api"
    ports:
      - 8080:8080
    networks:
      - cortex-net
    depends_on:
      - api

  pose-parser:
    build: "./cortex/parsers"
    command: "pose rabbitmq://mq:5672"
    networks:
      - cortex-net
    depends_on:
      - mq
    restart: on-failure
    volumes:
      - "cortex-data:/var/lib/data"

  feelings-parser:
    build: "./cortex/parsers"
    command: "feelings rabbitmq://mq:5672"
    networks:
      - cortex-net
    depends_on:
      - mq
    restart: on-failure
    volumes:
      - "cortex-data:/var/lib/data"

  depth-image-parser:
    build: "./cortex/parsers"
    command: "depth_image rabbitmq://mq:5672"
    networks:
      - cortex-net
    depends_on:
      - mq
    restart: on-failure
    volumes:
      - "cortex-data:/var/lib/data"

  color-image-parser:
    build: "./cortex/parsers"
    command: "color_image rabbitmq://mq:5672"
    networks:
      - cortex-net
    depends_on:
      - mq
    restart: on-failure
    volumes:
      - "cortex-data:/var/lib/data"

networks:
  cortex-net:

volumes:
  cortex-data:
